import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header/header';
import Footer from './components/Footer/footer';
import React from 'react';
import { QueryProvider } from './lib/query-provider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en" className="scroll-smooth" >
   <body className={inter.className}>
    <QueryProvider>
     <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">{children}</main>
      <Footer />
     </div>
    </QueryProvider>
   </body>
  </html>
 );
}
